UK_COUNTIES: dict[str, str] = {
    "bedfordshire": "Bedfordshire",
    "berkshire": "Berkshire",
    "bristol": "Bristol",
    "buckinghamshire": "Buckinghamshire",
    "cambridgeshire": "Cambridgeshire",
    "cheshire": "Cheshire",
    "cornwall": "Cornwall",
    "county durham": "County Durham",
    "cumbria": "Cumbria",
    "derbyshire": "Derbyshire",
    "devon": "Devon",
    "dorset": "Dorset",
    "east riding of yorkshire": "East Riding of Yorkshire",
    "east sussex": "East Sussex",
    "essex": "Essex",
    "gloucestershire": "Gloucestershire",
    "greater london": "Greater London",
    "greater manchester": "Greater Manchester",
    "hampshire": "Hampshire",
    "herefordshire": "Herefordshire",
    "hertfordshire": "Hertfordshire",
    "isle of wight": "Isle of Wight",
    "kent": "Kent",
    "lancashire": "Lancashire",
    "leicestershire": "Leicestershire",
    "lincolnshire": "Lincolnshire",
    "merseyside": "Merseyside",
    "norfolk": "Norfolk",
    "north yorkshire": "North Yorkshire",
    "northamptonshire": "Northamptonshire",
    "northumberland": "Northumberland",
    "nottinghamshire": "Nottinghamshire",
    "oxfordshire": "Oxfordshire",
    "rutland": "Rutland",
    "shropshire": "Shropshire",
    "somerset": "Somerset",
    "south yorkshire": "South Yorkshire",
    "staffordshire": "Staffordshire",
    "suffolk": "Suffolk",
    "surrey": "Surrey",
    "tyne and wear": "Tyne and Wear",
    "warwickshire": "Warwickshire",
    "west midlands": "West Midlands",
    "west sussex": "West Sussex",
    "west yorkshire": "West Yorkshire",
    "wiltshire": "Wiltshire",
    "worcestershire": "Worcestershire",
    "city of london": "City of London",
}
